spring.application.name: ping

aws.queue:
  producer: ping
  consumer: pong


cloud.aws:
  credentials:
    accessKey: ${AWS_ACCESS_KEY_ID:}
    secretKey: ${AWS_SECRET_ACCESS_KEY:}
    instanceProfile: true